@Tests = new Meteor.Collection('tests')
@Questions = new Meteor.Collection('questions')
@Sections = new Meteor.Collection('sections')
@TestSections = new Meteor.Collection('testSections')
@TestQuestions = new Meteor.Collection('testQuestions')
@MidSections = new Meteor.Collection('midSections')
@TestMidSections = new Meteor.Collection('testMidSections')